[workspace]
members = ["userspace", "common", "xtask"]

[patch.crates-io]
aya = { path = "/home/guillaume/Documents/Travaux/Mesure conso appli/aya/aya" }
aya-log = { path = "/home/guillaume/Documents/Travaux/Mesure conso appli/aya/aya-log" }
